version: '3.9'
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    env_file:
      - ../backend/.env
    depends_on:
      - postgres
    networks:
      - aidpa-net

  frontend:
    build:
      context: ../next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../next:/app
    depends_on:
      - backend
    networks:
      - aidpa-net

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: aidpa
      POSTGRES_PASSWORD: aidpa123
      POSTGRES_DB: aidpa_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - aidpa-net

volumes:
  pgdata:

networks:
  aidpa-net:
